spinnaker/deck-kayenta

- package.json
* chore: update core to 0.0.196; de-angularize help contents
> chore: bump package to 0.0.42

- package.json
- src/app.ts
- src/kayenta/canary.dataSource.ts
- src/kayenta/edit/configJsonModal.tsx
- yarn.lock
> Bump core to 0.0.237, update de-angularized services

- src/kayenta/edit/editMetricModal.tsx
- src/kayenta/report/detail/metricResultStats.tsx
> fix: placate linter

- src/kayenta/stages/kayentaStage/kayentaStage.html
- src/kayenta/stages/kayentaStage/kayentaStage.ts
Appearance when adding a new stage:
... and modifying the lifetime:
Appearance when lifetimeHours has been updated to lifetimeDuration:
fixes https://github.com/spinnaker/kayenta/issues/283
> feat(config): support kayenta stage lifetimes shorter than one hour

- src/kayenta/edit/metricList.tsx
- src/kayenta/edit/templates/templates.tsx
Closes https://github.com/spinnaker/deck-kayenta/issues/282
> feat: add tooltips

- src/kayenta/canary.help.ts
- src/kayenta/stages/kayentaStage/AnalysisType.tsx
- src/kayenta/stages/kayentaStage/kayentaStage.html
- src/kayenta/stages/kayentaStage/kayentaStage.ts
Addresses review comments from https://github.com/spinnaker/deck-kayenta/pull/326
> fix: address review comments for real time canary stage

- src/kayenta/canary.help.ts
- src/kayenta/stages/kayentaStage/kayentaStage.html
Also removes unused help keys.
Closes https://github.com/spinnaker/spinnaker/issues/3306
> fix: kayenta stage help

- src/kayenta/edit/metricList.less
- src/kayenta/edit/metricList.tsx
Closes #338 ([screenshot](https://screenshot.googleplex.com/ZFrFDgTnS9K))
> feat: add copy metric functionality, change metric icons to buttons

- .huskyrc
- build_scripts/checkLicenses.js
- package.json
@maggieneterval or @sbwsg please review.
> feat: check dependency licenses on precommit

- package.json
@fieldju is this what you're looking for? The prettier options come from `.prettierrc.json`.
Closes https://github.com/spinnaker/deck-kayenta/issues/355
> feat: add formatting helper

- settings.js
- src/kayenta/canary.settings.ts
- src/kayenta/stages/kayentaStage/kayentaStage.ts
> feat(stage): customizable name/description

- package.json
> chore: bump package to 0.0.62

- src/kayenta/canary.help.ts
- src/kayenta/stages/kayentaStage/AnalysisType.spec.tsx
- src/kayenta/stages/kayentaStage/AnalysisType.tsx
- src/kayenta/stages/kayentaStage/analysisType.component.ts
- src/kayenta/stages/kayentaStage/kayentaStage.controller.ts
- src/kayenta/stages/kayentaStage/kayentaStage.html
- src/kayenta/stages/kayentaStage/kayentaStage.less
Closes https://github.com/spinnaker/spinnaker/issues/3546
> fix: omit real time automatic mode for providers that don't support it

- src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
> fix(execution-summary): rework for new stage tree

- package.json
- Add metric deviation % (#391)
- Fix BG on metric config table headers (#392)
> chore(package): bump to 0.0.66

- src/kayenta/domain/ICanaryJudgeResult.ts
- src/kayenta/report/detail/metricResultsColumns.tsx
- src/kayenta/report/detail/multipleResultsTable.tsx
> fix(report): reportMetadata is... nullable

- package.json
feat(stage): add legacy siteLocal field for email notifications (#397)
feat(stage): add atlas-specific query scope support (#396)
> chore(package): bump to 0.0.68

- src/kayenta/canary.dataSource.ts
- src/kayenta/domain/ICanaryConfig.ts
- src/kayenta/edit/configJsonModal.tsx
- src/kayenta/edit/editMetricValidation.ts
- src/kayenta/edit/filterTemplateSelector.spec.tsx
- src/kayenta/edit/inlineTemplateEditor.spec.tsx
- src/kayenta/edit/metricList.tsx
- src/kayenta/layout/table/nativeTable.tsx
- src/kayenta/layout/table/nativeTableHeader.tsx
- src/kayenta/layout/table/table.tsx
- src/kayenta/layout/table/tableHeader.tsx
- src/kayenta/metricStore/atlas/atlasMetricConfigurer.tsx
- src/kayenta/metricStore/prometheus/metricConfigurer.tsx
- src/kayenta/metricStore/stackdriver/metricConfigurer.tsx
- src/kayenta/navigation/canary.states.ts
- src/kayenta/reducers/index.ts
- src/kayenta/reducers/selectedConfig.spec.ts
- src/kayenta/reducers/selectedConfig.ts
- src/kayenta/reducers/validators.ts
- src/kayenta/report/detail/graph/plotly/plotly-graph.tsx
- src/kayenta/report/detail/metricResultStats.tsx
- src/kayenta/report/detail/metricResultsColumns.tsx
- src/kayenta/report/detail/multipleResultsTable.tsx
- src/kayenta/report/detail/score.tsx
- src/kayenta/report/list/table.tsx
- src/kayenta/stages/kayentaStage/canaryRunSummaries.tsx
- src/kayenta/stages/kayentaStage/kayentaStage.controller.ts
- src/kayenta/stages/kayentaStage/kayentaStage.ts
- src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.controller.ts
- src/kayenta/utils/duration.spec.ts
this is the primary change: https://github.com/spinnaker/deck-kayenta/pull/403/commits/f4f2dc9c0004e20dd90055074baead52ac0358c2?utf8=%E2%9C%93&diff=split&w=1
> Annotate all AngularJS injection points, fix linter errors

- travis/installViaTravis.sh
basically the same thing as https://github.com/spinnaker/deck/pull/6611
there's currently nothing in the lockfile that's getting mutated at build time, but seems useful to add it in advance of any problems.
> chore(build): use --frozen-lockfile for travis

- src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
Sometimes things go wrong during cleanup and mark the kayenta stage TERMINAL even though the score passed. There was some logic in the transformer that would check `stage.isFailed` and add the canary score explanation message to the list of exceptions, which led to weird UX where you'd get an 'exception' that said `Final canary score 100.0 met or exceeded the pass score threshold.` in red.
I decided to switch that up so we check the score itself and whether it was above the marginal threshold in applicable spots, which also includes the color of the big score in the stage summary and the little label on the graph.
Also fixed a case where when the first `runCanary` stage fails it doesn't update the `canaryScoreMessage` on it's ancestor stage. Will probably also look at that from the …
> fix(execution): handle errors w/ passing scores better

- README.md
thanks @perek for pointing out
> Add/clarify yarn installation step in README

- src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
Last time we checked in with 'Erik's Misadventures in Stage Transformers', I was [fixing a full page crash](https://github.com/spinnaker/deck-kayenta/pull/434) as a result of a bad conditional. Today I'm thrilled to announce the latest installment, in which any pipeline with more than one `kayentaCanary` stage completely failed to do the necessary transforms on all but the very first stage of that type in the graph.
This is a really straightforward PR conceptually — it just makes this transformer aware of (and capable of handling) multiple `kayentaCanary` stages. That said, who knows what kind of magical next chapter in the series this PR might setup for us!
Before:
After:
> fix(stage): sometimes folks want multiple stages in their pipeline erik

- src/kayenta/metricStore/newrelic/metricConfigurer.tsx
Not sure why this wasn't caught in Travis from the get-go.
> fix(newrelic): Fix typo throwing errors

- build_scripts/checkLicenses.js
- package.json
- travis/installViaTravis.sh
- yarn.lock
Tested by running `yarn lib` and comparing file sizes to current file sizes on master and they look to be the same. Tests still run and pass.
> chore: upgrade to node 12

- src/kayenta/canary.dataSource.ts
Core was not bumped so reverting the breaking change
> fix: revert iconName

- src/kayenta/canary.dataSource.ts
Previously approved. Reverting the revert.
> feat(canary): Add iconName to canary data source

- package.json
> chore(package): bump version to v0.0.95

- src/kayenta/canary.dataSource.ts
I think pre-merge CI in this repo is different than post-merge CI... 🙈
> fix(imports): remove unused import

- package.json
> chore(build): bump version to 0.0.98

- package.json
- yarn.lock
Nothing fancy, but brings in new nav when running locally
> chore(package): bump spinnaker/core/amazon packages for standalone build

- package.json
> chore(build): bump version to 0.0.99

- src/kayenta/canary.module.ts
- src/kayenta/service/canaryConfig.service.ts
I expected this to be bigger but it isn't
> chore(prettier): reformat files with latest prettier

- .github/workflows/ci.yml
- .github/workflows/publish_lib.yml
- build_scripts/assert_package_bump.sh
- build_scripts/build_github_actions.sh
deck-kayenta is the last of the Spinnaker projects using Travis instead of Github Actions.
The configs and scripts are all based on similar ones found in deck. There's a chance they won't work correctly right out of the box.
> feat(build): attempt to build via Github Actions

- package.json
> chore(package): bump package to 0.0.100

- package.json
Includes the fix for re-running analysis
> chore(package): bump package to 0.0.103

- package.json
bump package version to get a release with the latest changes
> chore(package): bump package to 0.0.104

- src/kayenta/metricStore/prometheus/metricConfigurer.tsx
Currently there is no validation before use the MetricName property, which can produce a NPE if there is no value set.
backend validation https://github.com/spinnaker/kayenta/pull/820
`java.lang.NullPointerException: null at java.base/java.lang.StringBuilder.<init>(StringBuilder.java:124) ~[na:na] at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.buildQuery(PrometheusMetricsService.java:211) ~[kayenta-prometheus.jar:na] at com.netflix.kayenta.prometheus.metrics.PrometheusMetricsService.queryMetrics(PrometheusMetricsService.java:253) ~[kayenta-prometheus.jar:na]`
> fix(prometheus): validate metricName to prevent NPE on backend

- package.json
metric filters, a few other things
> chore(package): bump package to 0.0.106

- package.json
> chore(package): bump to 0.0.107

- package.json
* adding fail on indicators to metrics list
> chore(package): bump package to 0.0.108

- package.json
> chore(package): bump package to 1.0.2

- package.json
> rxjs externals

- src/kayenta/report/detail/metricResultsList.tsx
Right now, we'll only show tags when there are multiple metric results for a given metric.
Unfortunately, when filtering, we sometimes end up with single tags in a metric that will be rendered, so we collapse the tag, which is no good:
(unfiltered)
(filtered)
With this PR, we'll preserve the tags by computing the need before we do the filtering:
> fix(metrics): show tags in metric list when filtered

- package.json
> chore(package): bump to 1.0.5
