package.json, yarn.lock
requires running `yarn` locally to update packages
Before:
After: no error
=> fix: update spinnaker core version to correctly pull in HelpField component

src/kayenta/report/list/configLink.tsx, src/kayenta/report/list/reportLink.tsx, src/kayenta/report/list/table.tsx, src/kayenta/selectors/index.ts
fixes https://github.com/spinnaker/deck-kayenta/issues/292
=> fix: find canary config id from execution instead of app / config name pair

src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts, src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.html
Closes https://github.com/spinnaker/kayenta/issues/291 (the remaining issues had already been solved).
@anotherchrisberry I moved the overall score down to `kayentaStage.context` (I think it makes sense for it to live down there, so that's fine), but any mutations to the top-level stage object within the transformer are lost by the time it makes it to the execution controller. Any ideas? I'm assuming it's related to your recent changes around context.
=> fix: overall score

src/kayenta/edit/groupName.tsx
fixes https://github.com/spinnaker/deck-kayenta/issues/286
Before, strange input box follows user around UI:
After, change to tab name is committed and user is prompted to cancel the change if they want to navigate away:
=> fix: commit tab name change if user navigates away while editing

src/kayenta/canary.settings.ts, src/kayenta/domain/IMetricSetPair.ts, src/kayenta/report/detail/metricResultStats.tsx
We have consumers that need to be able to jump into the Atlas UI to dig deeper into a given metric for troubleshooting/analysis. I'm unsure of what an equivalent sort of link looks like for the other metric stores, and as a result have intentionally made this a bit special-cased to avoid choosing a bad/unhelpful indirection layer. If someone thinks this would be useful for other metric stores and wants to generalize it, that'd be awesome.
=> feat(report): add link to Atlas UI for graphing baseline vs. canary metrics

package.json
we skipped a version because somebody published without a commit.
=> chore: bump to 0.0.50

src/kayenta/stages/kayentaStage/canaryRunSummaries.tsx
Excludes the datadog provider from receiving the indicator as per https://github.com/spinnaker/kayenta/issues/283#issuecomment-397346975
Also: I've made the assumption that all metrics will receive the same number of data points for a given run.  If this isn't correct then I can include mention of exactly which metrics were below the confidence threshold.
The indicator is a small warning triangle:
And the message that appears when the triangle is hovered:
=> feat(executions): indicate canary runs that might be low-confidence

src/kayenta/canary.help.ts
When you're new to canaries time is hard. Ideally this should be a date picker, but for now can we add an example so when you're frantically googling iso-8601 and your canary doesn't work you have an easy way to figure out "oh I can't put `+00:00` I must put `Z`".
=> fix(help): give an example because time is hard

settings.js, src/kayenta/canary.settings.ts, src/kayenta/metricStore/atlas/atlasMetricConfigurer.tsx
Turns out that on Firefox (and probably Safari?) the Atlas web components we use to configure metrics require some polyfilling to register themselves. I decided to plop this in a setting given that it's a bit niche.
=> fix: support polyfilling for atlas web components

build_scripts/webpack.build.js, package.json, src/kayenta/canary.help.ts, src/kayenta/canary.module.ts, src/kayenta/domain/IKayentaStageConfig.ts, src/kayenta/domain/index.ts, src/kayenta/stages/kayentaStage/AnalysisType.tsx, src/kayenta/stages/kayentaStage/analysisType.component.ts, src/kayenta/stages/kayentaStage/forAnalysisType.component.ts, src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts, src/kayenta/stages/kayentaStage/kayentaStage.ts, src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.controller.ts, src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.html, src/kayenta/stages/kayentaStage/stageTypes.ts, webpack.common.js, yarn.lock
First pass at this, definitely some problems. The diff is not as bad as it looks, since it's mostly refactoring and moving things around. Most of the added logic / templates are from `canaryStage.js` in the main deck repo. I am definitely open to refactoring / moving towards react / testing but wanted to get this in.
Looks like this:
Known problems:
1). The machine type selector doesn't work when copying a GCE server group from a template, or when editing a GCE server group. It does work when creating one from scratch. This is a current bug for the GCE deploy stage, which is why I'm not fixing it here.
2). For stackdriver, we still expose "resource type", even though it feels as if, at least configuring canary for GCE, we should auto-pick `gce_instance`. I think that selector is going …
=> feat: real time automatic mode

package.json, yarn.lock
It appears that the recent upgrade of `@spinnaker/core` exposed the fact that `deck-kayenta` is running typescript 2, which is a major version behind the deck repo. Seems as if some newer syntax in one of `@spinnaker/core`'s declaration files caused TS 2 to fail. 
fyi @danielpeach
=> chore(deps): Upgrade typescript to 3.0.3

src/kayenta/domain/ICanaryConfig.ts, src/kayenta/edit/editMetricModal.tsx
This adds a read-only way to quickly check whether there are [effect size configurations](https://github.com/spinnaker/kayenta/pull/356) set for a given metric. We're not confident this will remain a useful option longer term, so currently the only way to configure them is by modifying the config JSON directly.
@skandragon @csanden
=> feat(metrics): Surface read-only effect sizes in metric config

src/kayenta/canary.less, src/kayenta/domain/ICanaryExecutionStatusResult.ts, src/kayenta/layout/table/index.ts, src/kayenta/layout/table/nativeTable.tsx, src/kayenta/layout/table/nativeTableHeader.tsx, src/kayenta/layout/table/tableColumn.ts, src/kayenta/report/list/configLink.tsx, src/kayenta/report/list/executionList.less, src/kayenta/report/list/link.tsx, src/kayenta/report/list/pipelineLink.tsx, src/kayenta/report/list/reportLink.tsx, src/kayenta/report/list/table.tsx
We've gotten a lot of feedback on the report list, including:
- It's pretty unhelpful in terms of differentiating one run from another when the same config is used across multiple use cases.
- The `Pipeline` link is frustrating because it shows up when there's no pipeline, and then links to a broken page.
- It's difficult to navigate around because the `Report` link itself is all the way to the right and not particularly noticeable.
This is an attempt to solve some of those issues without doing a full rethink of the report list, which ought to happen at some point but will take a larger time investment.
A brief summary:
- The date, score, report link and a new relative date are all grouped together on the far left.
- The pipeline link is hidden when there's no parent pipeline.
- To …
=>  feat(executions): Re-org execution list, add locations and scopes

src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html
This just wires up the React code path for clone server group modals, which enables Amazon to do work with Real Time Automatic mode without much extra effort. Hasn't been heavily tested so may end up requiring some patches later on if we discover things in production.
Also opens up support for Titus, but I think there's some stuff in `@spinnaker/titus` that needs fixing to fully support that.
=> feat(stage): Add support for Amazon in Real Time Automatic mode

src/kayenta/edit/templates/templates.less, src/kayenta/edit/templates/templates.tsx
Change template icons to buttons to match style changes in #340 ([screenshot](https://screenshot.googleplex.com/rujH17OWoNQ))
=> feat: change edit and remote template icons to buttons

src/kayenta/domain/IKayentaAccount.ts, src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html
Metric accounts now support two additional fields: `recommendedLocations` and `locations`, which can suggest location values to pick from for that account. This updates the stage config UI to handle three cases:
- There's no `recommendedLocations` or `locations`, we do what we were doing before (text field).
- There's _only_ `recommendedLocations` or only `locations`, we show a dropdown for the list with options.
- There's both `recommendedLocations` and `locations`, we show the dropdown with just `recommendedLocations` but give an option to toggle for all `recommendedLocations` + `locations`.
There's subtleties beyond this, like opening up an existing stage with a location that's not supported anymore, but in general that's the idea. I decided to stay away from having some option to use …
=> feat(stage): Add support for predefined locations, atlas scope fields

settings.js, src/kayenta/canary.settings.ts, src/kayenta/domain/ICanaryExecutionStatusResult.ts, src/kayenta/manualAnalysis/ManualAnalysisModal.tsx, src/kayenta/report/list/table.tsx, src/kayenta/service/canaryRun.service.ts
Very barebones initial pass at allowing ad-hoc analysis (a.k.a. manual executions).
Initially, this will available behind a feature flag and show up as a `Start Manual Analysis` button on the report list. The workflow is effectively the same as setting up a 'retrospective' analysis in the stage config, but doesn't keep any state hanging around before/after. Some general notes:
- It doesn't support multiple scopes yet, and hasn't been hooked up to the details for the chosen config to support scopes with names other than 'default'.
- I _think_ the `resourceType` picker works, but haven't had a chance to test it out for real.
- The experience after submitting is pretty bad, right now we just fire and forget if the task is submitted successfully, with a note to check the report list for it to …
=> feat(executions): Add first pass at manual execution support

src/kayenta/edit/editMetricModal.tsx, src/kayenta/edit/filterTemplateSelector.spec.tsx, src/kayenta/edit/filterTemplateSelector.tsx, src/kayenta/edit/templates/templates.tsx, src/kayenta/reducers/selectedConfig.ts, src/kayenta/reducers/templates.spec.ts
Also fixes bug where an update to a filter template name isn't reflected in the metric configs.
=> feat: show templates in metric config editor

.eslintrc, src/kayenta/actions/creators.ts, src/kayenta/actions/index.ts, src/kayenta/manualAnalysis/ManualAnalysisModal.tsx, src/kayenta/metricStore/prometheus/domain/IPrometheusCanaryMetricSetQueryConfig.ts, src/kayenta/metricStore/prometheus/metricConfigurer.tsx, src/kayenta/reducers/prometheusMetricConfig.spec.ts, src/kayenta/reducers/prometheusMetricConfig.ts, src/kayenta/stages/kayentaStage/kayentaStage.html
- removes resource type selector in stage config
- removes conflict between linter and formatter
=> feat: select resource type in prometheus edit metric modal

src/kayenta/canary.help.ts, src/kayenta/domain/IKayentaStageConfig.ts, src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/utils/duration.spec.ts, src/kayenta/utils/duration.ts
Closes [#3502](https://github.com/spinnaker/spinnaker/issues/3502):
- Adds "Delay Before Cleanup" field to Realtime (Automatic) Canary Analysis stage UI
- Move `Duration` parsing logic out of controller to be shared by `lifetimeDuration` and `delayBeforeCleanup` fields since both are stored on state as hours/minutes but saved to the stage as duration strings
- Change "Lifetime Duration" field to type number to match "Delay Before Cleanup" field, add min=0 to hours and min=0/max=59 to minutes
- Set "Step" min to 0
=> feat: add Delay Before Cleanup field to stage UI (#3502)

src/kayenta/canary.less
Before:
1. Scrolling disabled in firefox
2. Padding at bottom incorrect when screen is scrolled
After:
Scrolling in FF and margin at bottom:
=> fix(layout): correct firefox scrolling in flex container and spacing at bottom

src/kayenta/stages/kayentaStage/kayentaStage.controller.ts
Turns out Orca passes an ASG as the scope for infrastructure generated as part of a run in automatic mode, but we're currently telling atlas it's a cluster.
=> fix(stage): scope Atlas-backed Real Time Automatic configs to ASG, not cluster

src/kayenta/stages/kayentaStage/kayentaStage.controller.ts
Per a conversation from a little while ago, this switches the detail for server group pairs from `control`/`experiment` to `baseline`/`canary`, which better matches the rest of the user-facing terminology. It also adds the option to provide multiple pairs in a single stage.
=> fix(stage): rename Server Group detail, allow multiple pairs

src/kayenta/components/canaryScore.component.less, src/kayenta/components/canaryScore.tsx, src/kayenta/report/detail/detail.less, src/kayenta/report/detail/detail.tsx, src/kayenta/report/detail/header.less, src/kayenta/report/detail/header.tsx, src/kayenta/report/detail/reportMetadata.tsx, src/kayenta/stages/kayentaStage/canaryRunSummaries.tsx
fixes the detail view header, and allows it to be collapsed for more vertical real estate.
=> fix(kayenta-details): ux bandaid for details view

yarn.lock
Dependabot recommended we bump the version of `marked` to patch a security vulnerability in deck, figured I would take care of it here as well (Deck PR [here](https://github.com/spinnaker/deck/pull/5935)).
=> chore(dependencies): bump marked version to patch security vulnerability

package.json
Bump package version to 0.0.65 so [PromQL queries](https://github.com/spinnaker/deck-kayenta/commit/27ed19c57a6a2ed934f97e9c9810e47dee5919b4) can be included with 1.11.x.
=> chore: bump to 0.0.65

src/kayenta/report/detail/metricResultDeviation.tsx, src/kayenta/report/detail/metricResultsColumns.tsx, src/kayenta/report/detail/multipleResultsTable.tsx
Right now I'm pulling this out of `resultMetadata` and just not showing if it doesn't exist — do we expect to have this for every judge? Can always tweak when/how it shows up in the future.
fyi @skandragon @csanden
=> feat(report): add per-metric deviation percentage

src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html
In the atlas world, you can have a scope be a raw atlas query, as opposed to a cluster/asg.
This mostly just adds a specific value for the `type` field we already use in `extendedScopeParams`, but it also changes the scope inputs to `<textarea>`s to make it easier to work with long atlas query strings.
=> feat(stage): add atlas-specific query scope support

settings.js, src/kayenta/canary.help.ts, src/kayenta/canary.settings.ts, src/kayenta/domain/IKayentaStageConfig.ts, src/kayenta/stages/kayentaStage/kayentaStage.controller.ts, src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/stages/kayentaStage/kayentaStage.ts
At Netflix, we use an internal system to send emails when canary reports complete. In order to facilitate that for the time being, this adds a feature-flagged UI for populating kayenta's `siteLocal` field with a list of emails to notify. We're already scoping out a mechanism to do this notification generically in OSS-land (and subsequently move to that model internally), but until then most of the new fields are called `legacyXYZ` to call out that they are not likely to be around for long.
=> feat(stage): add legacy siteLocal field for email notifications

yarn.lock
Fixes failed `fsevents` build on macosx
```
warning Error running install script for optional dependency: "/Users/cthielen/netflix/spinnaker/deck-kayenta/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/cthielen/netflix/spinnaker/deck-kayenta/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.34
node-pre-gyp info using node@10.15.1 | darwin | x64
node-pre-gyp info check checked for \"/Users/cthielen/netflix/spinnaker/deck-kayenta/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.1/fse-v1.1.1-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 …
```
=> chore(package): Use latest fsevents (update to lockfile only)

src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts, src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.controller.ts, src/kayenta/stages/kayentaStage/stageTypes.ts
During an automatic deployment, the execution summary gets pretty cluttered with synthetic stages for all the various steps in a parallel baseline + canary deploy. As a side effect it can get pretty hard to find the stage with the actual scores. Our hypothesis is that if a step in the deployment is _successful_, there's not enough value in showing it to justify the noise.
I chose to hide all successful deployment steps _except_ the two `createServerGroup` stages, because they each contain a succinct summary of what was deployed and a link out to the server group. Those two stages will also now appear as `Deploy {baseline|canary} in {locations}`, which should make the steps pretty clear. In the deployment success case (including when the analysis step is failed due to a low score), we go …
=> feat(executionSummary): hide noisy deployment stages, make rendering less flakey

src/kayenta/stages/kayentaStage/CanaryExecutionLabel.tsx, src/kayenta/stages/kayentaStage/kayentaStage.ts
The older canary stage does a kind of nice thing where it adds the overall score/result to the execution labels and tooltips. This mostly does a 1:1 port of that into Kayenta:
=> feat(stage): Add score to execution labels

package.json, src/kayenta/report/list/table.tsx, yarn.lock
Fix canary report table and upgrade to bootstrap 3.4.1
Canary report has garbled scores and information if the scope is too long. Temporarily fixed it to make it usable. Upgraded to bootstrap 3.4.1 since this is on the older version with a few XSS vulnerabilities.
=> fix(style): Table should render correctly with large scopes.

src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
I definitely realized that stage transformers are called for every execution even if they don't contain a specific stage type, this was simply a piece of very subtle performance art that involved breaking everyone's executions
=> fix(executionSummary): don't npe on basically every execution

src/kayenta/edit/configList.less, src/kayenta/edit/configList.tsx
In the list of canary configs the nice, big sidebar items have a hover state _and_ a pointer cursor, but the actual `<UISref>` has been on this teeny tiny little link you have to know to click despite our affordances lying to you:
This moves the `<UISref>` up to cover the entire `<li>` so the affordances match reality. I yanked out the `<a>` entirely, and the text now looks a little more like a normal sidebar item rather than a sub-link inside a bigger clickable thing:
=> fix(configs): make the config list click target humanely sized

src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
Turns out it's rude to take other people's `createServerGroup` stages and never give them back
=> fix(executions): don't steal createServerGroup stages from other owners (oops)

package.json, src/kayenta/canary.help.ts, src/kayenta/report/detail/graph/chartjs/chartConfigFactory.ts, src/kayenta/report/detail/graph/chartjs/graph.tsx, src/kayenta/report/detail/reportMetadata.tsx, src/kayenta/stages/kayentaStage/canaryRunSummaries.tsx, src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/stages/kayentaStage/kayentaStageExecutionDetails.html
Associated Orca Pull: https://github.com/spinnaker/orca/pull/2836
We have added support for offsetting canaries baseline scope to enable comparison across two different windows in time. This allows for checking metrics against previous known values enabling canaries during rollouts, and checking the effect of a deployment on overall metrics without deploying a baseline scope.
Added functionality:
- add support for 2 x-axis
- add support for hiding an axis
- added displays of the offset value where relevent
=> feat(canary) - add support for displaying time offset canaries

src/kayenta/canary.less, src/kayenta/edit/configDetailHeader.tsx, src/kayenta/edit/configJsonModal.tsx, src/kayenta/edit/copyConfigButton.tsx, src/kayenta/edit/editMetricModal.tsx, src/kayenta/edit/metricList.tsx, src/kayenta/edit/nameAndDescription.tsx
Today when you view a config in an app that doesn't 'own' that config, we are _theoretically_ supposed to switch to a read only view. Turns out, we don't really do that and instead we really just disable the 'Delete' buttons on stuff with everything else left editable. For added fun, if you try to click 'copy' it opens up a copied config but doesn't let you edit it and therefore it's impossible to save. This has caused some confusion at Netflix, especially because there's no mention of _why_ editing is disabled.
My attempt to reduce confusion is pretty low effort (this doesn't come up too often):
- _Actually_ disable everything on the config page that has to do with write operations (copy, saving changes to metrics, updating the JSON manually, etc.)
- Add a new warning at the top of the …
=> feat(config): less confusing UX when viewing a read only config

src/kayenta/stages/kayentaStage/kayentaStage.transformer.ts
Apparently when I write transformers I accidentally make them very greedy, as this is the second case of `KayentaStageTransformer` stealing other stages and using them as its own.
Turns out that early in the lifecycle of `kayentaCanary` stages they don't actually have an `intervalStageId`, which makes sense. Top level stages don't have `parentStageId`s, which also makes sense. The only thing that doesn't make sense is the conditional I wrote which took any stages whose `parentStageId` matched the value of `intervalStageId` (when both are sometimes `undefined`) and claimed them as belonging to the `kayentaCanary` stage.
Sometimes this bug resulted in weird missing stages, other times it blew up the pipeline graph code and led to an unrecoverable full page crash.
cc @gregorymfoster
=> fix(stage): don't steal other stages when no intervalStageId exists

src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/stages/kayentaStage/kayentaStage.ts
The stage config's controller already defaults to a non-null value in all the cases i've been able to identify, but we ran into a snag internally where someone was migrating their old stages over to the `kayentaCanary`  stage and somehow the `type` field got dropped from the underlying JSON. They were unaware since we didn't show any sort of validation errors — this should theoretically fix that.
=> fix(stage): mark 'Scope Type' as required for non-automatic Atlas stages

package.json, src/kayenta/report/detail/graph/semiotic/config.less, src/kayenta/report/detail/graph/semiotic/timeSeries.less, yarn.lock
There are a couple of vars used by the chart stylesheets that are (I think?) older color vars which don't start with `--color-`. Turns out we somehow still have those in our internal build which I think is how they made it in here, but in the standard `deck` configuration it causes a completely black background to show up on time series charts rather than using the standard background color.
I'm also bumping `@spinnaker/styleguide` while I'm in here because it was pinned to an old version. Don't know for sure whether we even need it listed as a dep of the library these days 🤔
=> fix(report): use '--color-' qualified vars, upgrade styleguide

src/kayenta/navigation/canary.states.ts
Turns out we've been implicitly relying on bypassing `UISref`'s transition logic, and [now that core no longer does that for us](https://github.com/spinnaker/deck/pull/7064) navigating to the top level report and config states from the nav is broken.
The actual culprits were 1. listing the top level states as abstract 2. not redirecting to the appropriate default state explicitly.
=> fix(report, config): don't blow up when navigating to top level config/report states

src/kayenta/stages/kayentaStage/canaryRunSummaries.tsx, src/kayenta/stages/kayentaStage/kayentaStage.html, src/kayenta/stages/kayentaStage/kayentaStage.ts
Closes https://github.com/spinnaker/deck-kayenta/issues/453
- In the canary stage execution details, there is a tooltip that displays a formatted start and end time, which matches the formatting of the Last Updated column. However, the timestamp that is actually copied to the clipboard is formatted as an ISO-8601 instant, which is what the start and end time inputs of the Retrospective Analysis field expects. Clarify the formatting in the tooltip text.
- Also, validate that the Retrospective Analysis start and end times are indeed formatted as ISO-8601 instants using a scary regex from the internet.
=> fix(stage): improve start and end timestamp validation and help text

src/kayenta/actions/creators.ts, src/kayenta/metricStore/prometheus/metricTypeSelector.less, src/kayenta/metricStore/prometheus/metricTypeSelector.spec.tsx, src/kayenta/metricStore/prometheus/metricTypeSelector.tsx, src/kayenta/middleware/epics.ts
Closes https://github.com/spinnaker/spinnaker/issues/4672#issuecomment-514746344
Relates to spinnaker/kayenta#598
- Unblocks users with multiple configured Prometheus accounts from searching for Prometheus metrics against different accounts when configuring a metric. Metric search will query against the alphabetically first account by default. Users can select a different account to search against, but the selected account will not be persisted with the configured metric since we want to keep the metric config account-agnostic.
- Does not change functionality for users with only one Prometheus account.
=> fix(prometheus): handle multiple accounts in metric type search

src/kayenta/metricStore/datadog/metricConfigurer.tsx
The typeahead/dropdown selector for Datadog metrics prevented the proper
prefixing of the aggregator function (avg, max, min, sum).  This adds
those as radio button options and assembles the metric name properly, so
the backend Kayenta implementation doesn't have to change.
=> fix(datadog):  Add aggregator selector to Datadog

src/kayenta/metricStore/index.ts, src/kayenta/metricStore/newrelic/index.ts, src/kayenta/metricStore/newrelic/metricConfigurer.tsx
This is a small patch to make sure the graph view for New Relic canaries
doesn't crash.  This will soon be extended to properly handle UI
configuration of New Relic canary configs, but wanted to get this in
first, since crashes are bad.
Ref:  https://github.com/spinnaker/spinnaker/issues/4389
Kudos to @imakewebthings for pointing out the underlying cause.
=> fix(newrelic): Make New Relic canary graphs work

src/kayenta/actions/creators.ts, src/kayenta/actions/index.ts, src/kayenta/metricStore/newrelic/domain/INewRelicMetricDescriptor.ts, src/kayenta/metricStore/newrelic/index.ts, src/kayenta/metricStore/newrelic/metricConfigurer.tsx, src/kayenta/reducers/data.ts, src/kayenta/reducers/selectedConfig.ts
This adds the simplest of UI to let users edit the New Relic select query in the canary config without having to edit the JSON directly.
=> fix(newrelic):  Add UI to edit select query

src/kayenta/actions/creators.ts, src/kayenta/edit/editMetricModal.tsx, src/kayenta/edit/editMetricValidation.spec.ts, src/kayenta/edit/editMetricValidation.ts, src/kayenta/edit/metricList.tsx
Closes https://github.com/spinnaker/spinnaker/issues/4877
Per discussion on this [PR](https://github.com/spinnaker/deck-kayenta/pull/457), we should default the scope name to default and hide the field in the UI.
=> feat(configs): hide scopeName field in metric config

src/kayenta/canary.dataSource.ts
Depends on https://github.com/spinnaker/deck/pull/8120 merge and then bumping @spinnaker/core. 
> Given the svg icon loader (#8056) and the upcoming Nav restructure, it is a good time to migrate the nav bar icons to svgs.
> In order to do this, the ApplicationDataSource type now has an iconSvg attribute. Once this change propagates to all data sources in deck and deck-kayenta, a follow-up PR will update the NavIcon component to utilize dataSource.iconSvg instead of the current dataSource.icon, which points to the font awesome icon.
=> feat(kayenta): Add svg name to dataSource

src/kayenta/canary.dataSource.ts
Closes https://github.com/spinnaker/spinnaker/issues/5588
Do not register canary data source unless the canary feature flag is enabled as all requests are guaranteed to fail.
=> fix(canary): make data source conditional on feature flag

README.md, src/kayenta/report/detail/detail.tsx, src/kayenta/report/detail/reportExplanation.less, src/kayenta/report/detail/reportExplanation.tsx
This change will surface the classification reason (if available) to help users understand why their canary may have failed outside of pure scoring.
This does not change the appearance of success cases:
=> feat(report/graph): Add a section for surfacing the report explanation/classification reason

src/kayenta/report/detail/graph/semiotic/tooltip.tsx
Running into the following error with v0.0.89 in our custom deck wrapper project
I was able to fix it by checking out the v0.0.89 code base and adding the following patch.
https://github.com/spinnaker/deck-kayenta/compare/v0.0.89...armory:v0.0.89-hotfix-1
@erikmunson, I was not able to run `yarn lib` on master to test this with `yarn link`
```
ERROR in ./src/kayenta/report/detail/reportExplanation.tsx
Module parse failed: /Users/fieldju/dev/spinnaker/deck-kayenta/node_modules/happypack/loader.js?id=ts!/Users/fieldju/dev/spinnaker/deck-kayenta/src/kayenta/report/detail/reportExplanation.tsx Unexpected token (6:33)
You may need an appropriate loader to handle this file type.
| const react_redux_1 = require("react-redux");
| require("./reportExplanation.less");
...
...
```
With the fix and …
=> fix(tooltip): fixed uncaught invariant violation, when deck-kayenta is used in custom deck wrapper

src/kayenta/report/list/table.tsx
Kind of silly we don't show the "Start Manual Analysis" button unless there is a report history.
=> fix(manualExecution): show Start Manual Execution button regardless of report history

src/kayenta/components/canaryScores.tsx, src/kayenta/manualAnalysis/ManualAnalysisModal.tsx, webpack.common.js
I ended up spending way more time on this than I meant to but did not go so far as to rewrite it using the Deck form library stuff.
* surfacing validation errors for each field
* adding a popover with the errors to the disabled submit button
**Some error messages (only showing on fields that have been filled out)**
**Error messages in popover on disabled submit button**
**Properly filled out, button is enabled**
=> feat(analysis): show error messages on manual analysis modal

src/kayenta/canary.dataSource.ts
Fixes: https://github.com/spinnaker/spinnaker/issues/5939
In a [previous PR](https://github.com/spinnaker/deck-kayenta/pull/494), I gated registration of the canary data source using the `SETTINGS.feature.canary` flag, which I have since learned is actually intended to only gate the legacy canary modules in Deck. Fix this by reading from the correct CanarySettings flag.
=> fix(config): use non-legacy canary flag to gate data source

src/kayenta/domain/ICanaryExecutionStatusResult.ts, src/kayenta/report/detail/detail.tsx, src/kayenta/report/detail/reportException.tsx, src/kayenta/report/detail/sourceLinks.tsx, src/kayenta/selectors/index.ts, src/kayenta/service/canaryRun.service.ts
We sometimes see a `Could not load canary report.` message when there was an error generating the report.
The change here: if an `exception` object is present, and there are no results in the report, display the error message.
This is one of those annoying things in Spinnaker where there is no clear contract for error messages, but they typically seem to be in the detail object, so we'll try to extract it from there.
Example:
Also including a link to the JSON source of the report.
=> fix(report): surface exceptions when generating report

src/kayenta/actions/creators.ts, src/kayenta/actions/index.ts, src/kayenta/canary.dataSource.ts, src/kayenta/canary.settings.ts, src/kayenta/canary.tsx, src/kayenta/navigation/canary.states.ts, src/kayenta/reducers/app.ts, src/kayenta/reducers/data.ts, src/kayenta/report/list/table.tsx, src/kayenta/service/canaryRun.service.ts
Resolves a TODO from two years ago and lets users show more than the most recent 20 canary reports for a given application.
By default, we'll show the most recent 20, but users can pick 50, 100, 200. Some people will notice the count is in the URL and will try to change it to some very large number and will feel very smart that they did that and it worked.
There is still no way to filter the report list, and there is no pagination. Those might come later. Honestly, this was about 100 times harder than I expected, but that was mostly because I don't work with redux enough to know it well.
Also, the `autoActivate` functionality of the data source appears to be broken: when navigating within a data source, intra-source navigation will fire both the activate and de-activate calls right after …
=> feat(report): allow users to control number of reports shown

src/kayenta/domain/ICanaryExecutionStatusResult.ts, src/kayenta/manualAnalysis/ManualAnalysisModal.tsx, src/kayenta/report/list/table.tsx
If a user wants to tweak a canary config, then regenerate a report, it's tedious right now, and it shouldn't be. We have all the information we need in the report execution.
This PR adds the ability to re-run a report by mapping the values from the original report to the initial values in the Start Manual Execution modal.
I've only tested this against Atlas. It's possible there are problems or issues with these mappings for other metric stores.
=> feat(reports): add rerun report action

src/kayenta/report/detail/metricResultsColumns.tsx, src/kayenta/report/detail/multipleResultsTable.tsx
There are long metric names right now that blow out the side of the list.
The changes introduced in this PR are not perfect, but I think it's about as good as we can get with the current layout.
_Before:_
_After:_
=> fix(report): break long metric names in list view

src/kayenta/manualAnalysis/ManualAnalysisModal.tsx
When clicking the "Start Manual Analysis" button, it makes sense to default the scope type to "cluster". But, if the user is re-running an existing report, we should just use whatever was set in the initial run.
=> fix(rerun): do not override scope type when re-running analysis

README.md
Publishing is now automatic, so these instructions are incorrect.
=> chore(readme): update readme instructions for publishing via GHA

src/kayenta/index.ts, src/kayenta/layout/index.ts, src/kayenta/metricStore/index.ts
Hi, exporting modules and naming default objects on Deck-Kayenta, to make the project easy to extend
=> chore(modules): exporting modules for extensibility

src/kayenta/report/detail/metricResultActions.tsx
If a metric is grouped and we generate an Atlas link, the legend is not very useful:
We can include the tag and make it a little easier to understand what you're looking at (note the order is different than above because it's alphabetized, and this is a subset of all the entries in the legend):
=> feat(atlas): include tags in Atlas legend links

src/kayenta/actions/creators.ts, src/kayenta/actions/index.ts, src/kayenta/edit/metricList.less, src/kayenta/reducers/selectedRun.ts, src/kayenta/report/detail/metricResultsClassificationFilters.tsx, src/kayenta/report/detail/metricResultsList.tsx
We have a lot of big reports. When something fails, it can be really hard right now to see what caused it:
Was it just the one metric at the top that failed? There are almost 300 metrics in this list, who knows!
This PR adds very simple filters based on metric classification:
=> feat(report): add metric filters

src/kayenta/report/detail/graph/semiotic/boxplot.less, src/kayenta/report/detail/graph/semiotic/differenceArea.tsx, src/kayenta/report/detail/graph/semiotic/semioticGraph.less, src/kayenta/report/detail/graph/semiotic/timeSeries.tsx, src/kayenta/report/detail/graph/semiotic/utils.ts
1. Changes on timeSeries.tsx:
- Rename a bunch of variables on timeSeries.tsx.
- Minimap xExtent bug is fixed in semiotic and we don't need a few interim objects as a workaround.
2. Change on differenceArea.tsx:
- Add top margin for the delta icon.
3. Others:
- Update css attribute for the svg line graphs. The lines should look more crisp now.
=> feat(report/graph): clean up chart code-debt & update svg style

src/kayenta/edit/metricList.less, src/kayenta/edit/metricList.tsx
It's hard to tell how a metric behaves without clicking "Edit":
This PR addresses this by including the direction of the metric. If it's critical, the indicators are shown in red and the tooltip indicates the criticality:
=> feat(metrics): include metric failure direction info in metric list

src/kayenta/report/detail/metricResultActions.tsx
It's not a URL that's being copied, just a query fragment
=> fix(atlas): reword "Copy Metric URL" button text

package.json
BREAKING CHANGE The @spinnaker/kayenta package is now published as ESM, and not as a UMD bundle.
=> feat: release 1.0.0

src/kayenta/report/detail/graph/semiotic/boxplot.tsx, src/kayenta/report/detail/graph/semiotic/histogram.tsx
semiotic 2.0.0 uses a different key for `axes`
=> fix(charts): fix axes key

package.json, rollup.config.js, src/kayenta/report/detail/graph/semiotic/boxplot.tsx, src/kayenta/report/detail/graph/semiotic/histogram.tsx, src/kayenta/report/detail/graph/semiotic/semioticGraph.less, src/kayenta/report/detail/metricResultsClassificationFilters.tsx, yarn.lock
I don't understand the plugin stuff at all and I'm not interested in learning it.
However, I found if I include "semiotic" in the list of externals, we can build kayenta into a library that deck can consume using semiotic 1.20.6.
Why does this work? I don't know! It even works if I remove the semiotic dependency from deck altogether...which we should, right?
Anyway, this PR:
* removes all the hacky stuff we were trying to do to make semiotic 2.x-rc work
* adds "semiotic" in the externals of the rollup/plugin config
* (unrelated) replaces an onClick handler with an onChange handler to make a warning go away
=> fix(graphs): use semiotic 1.x, set as external

rollup.config.js, src/kayenta/middleware/epics.ts
There are breaking changes in `rxjs` 6, which deck is upgrading to. However, if we upgrade to `rxjs` 6 we also have to update to `redux-observable` 1.0 and that requires us to upgrade `redux` as well. 
I can't commit to that effort, so we'll pin `rxjs` to 5.x in kayenta and include it in the bundle.
=> chore(rxjs): switch back to bundling rxjs 5.x instead of migrating to rxjs 6

package.json, src/index.ts
In order to be able to create plugins for Deck-Kayenta we need the classes exported in order for them to be available to the Deck plugin framework.
=> feat: Expose spinnaker/kayenta to plugin system

package.json, src/kayenta/edit/changeMetricGroupModal.tsx, src/kayenta/edit/configDetailHeader.tsx, src/kayenta/edit/configJsonModal.tsx, src/kayenta/edit/copyConfigButton.tsx, src/kayenta/edit/createConfigButton.tsx, src/kayenta/edit/editMetricEffectSizes.tsx, src/kayenta/edit/editMetricModal.tsx, src/kayenta/edit/filterTemplateSelector.tsx, src/kayenta/edit/groupName.tsx, src/kayenta/edit/groupTabs.tsx, src/kayenta/edit/groupWeight.tsx, src/kayenta/edit/inlineTemplateEditor.tsx, src/kayenta/edit/judgeSelect.tsx, src/kayenta/edit/metricList.tsx, src/kayenta/edit/metricStoreSelector.tsx, src/kayenta/edit/nameAndDescription.tsx, src/kayenta/edit/openDeleteModalButton.tsx, src/kayenta/edit/saveConfigButton.tsx, src/kayenta/layout/disableable.tsx, src/kayenta/reducers/app.ts
Adds a "disableConfigEdit" flag into the "Canary" settings of deck which will make the config edit portions of the canary config ui read only for all configs if the flag is set to true. This feature is intended for cases where the canary configs are being managed via code and deployed/updated via api calls to prevent drift and issues arising from manually made canary changes.
Images below show the state of the edit panels with the flag enabled.
=> feat(kayenta): Add Flag to Disable Canary Config UI Editing
